name: product_catalogue
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  auto_route: ^10.2.2
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  realm: ^20.2.0
  retrofit: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  retrofit_generator: ^9.6.0
  auto_route_generator: ^10.1.0
  freezed: ^3.0.6

flutter:
  uses-material-design: true
